### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Erhushenshou** [esimiele/VMAT-TBI#7]
Bug: When adding optimization, it reported can't add jaw tracking to beams because not supported. 
![image](https://user-images.githubusercontent.com/38848249/165229180-d07a6d3f-db12-4161-afb3-4265bb75753a.png)
![image](https://user-images.githubusercontent.com/38848249/165229214-d665a912-7182-43db-be87-3b862cee5841.png)
But when testing on Tbox, the code ran smoothly. Could you figure out this problem?

**Comment by Erhushenshou** [comment]
The log file is copied here. 
There was a problem while executing the script 'VMATTBIautoPlan_v1.2.esapi.dll'.

Cannot add Jaw tracking parameter. None of the beams support Jaw tracking.


\\img\Va_Transfer\Eclipse Script\VMAT-TBI-beta\VMAT-TBI-beta\ESAPI\Plugins\VMATTBIautoPlan_v1.2.esapi.dll



System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> VMS.TPS.Common.Model.ScriptExecutionException: There was a problem while executing the script '\\img\Va_Transfer\Eclipse Script\VMAT-TBI-beta\VMAT-TBI-beta\ESAPI\Plugins\VMATTBIautoPlan_v1.2.esapi.dll' (ESAPI: VMS.TPS.Common.Model.API, Version=1.0.300.11, Culture=neutral, PublicKeyToken=305b81e210ec4b89).  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Cannot add Jaw tracking parameter. None of the beams support Jaw tracking.


   at VMS.TPS.Common.Model.ValidationRuleCallback.Throw()


   at VMS.TPS.Common.Model.ValidationRuleComposite.Throw()


   at VMS.TPS.Common.Model.PlanSetup.AddVMATJawTrackingParameter()


   at VMS.TPS.Common.Model.API.OptimizationSetup.set_UseJawTracking(Boolean value)


   at VMATTBIautoPlan.UI.setOptConst_Click(Object sender, RoutedEventArgs e) in C:\Users\Varian\Desktop\VMAT-TBI-beta\VMAT-TBI-beta\ESAPI\Projects\VMATTBIautoPlan\UI.xaml.cs:line 1272


   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)


   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)


   at System.Windows.Controls.Primitives.ButtonBase.OnClick()


   at System.Windows.Controls.Button.OnClick()


   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)


   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)


   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)


   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)


   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)


   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)


   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)


   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)


   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)


   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)


   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)


   at System.Windows.Input.InputManager.ProcessStagingArea()


   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)


   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)


   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)


   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)


   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)


   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)


   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)


   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)


   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)


   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)


   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)


   at System.Windows.Window.ShowHelper(Object booleanBox)


   at System.Windows.Window.ShowDialog()


   at VMS.TPS.Script.Execute(ScriptContext c) in C:\Users\Varian\Desktop\VMAT-TBI-beta\VMAT-TBI-beta\ESAPI\Projects\VMATTBIautoPlan\VMATTBIautoPlan.cs:line 39


   --- End of inner exception stack trace ---


   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)


   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)


   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)


   at VMS.TPS.Script.Engine.InvokeMethod(Object obj, String methodName, Object[] parameters)


   at VMS.TPS.Script.Engine.Execute(String fileName)


   --- End of inner exception stack trace ---


   at VMS.TPS.Script.Engine.Execute(String fileName)


   at VMS.TPS.Script.Extension.Execute(IntPtr parentWindow)


   --- End of inner exception stack trace ---


   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)


   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)


   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)


   at vhost.TpsNetExtension.Execute(TpsNetExtension* , HWND__* parentWindowHandle)

**Comment by esimiele** [comment]
It seems like your machine does not support jaw tacking for IMRT/VMAT beams. I wrote the code so it automatically sets jaw tracking to true (no check performed to see if jaw tracking could be used with the selected linac). Code was revised to now try to add jaw tracking, but report to the user if it failed (code should not crash now). Fix pushed to the beta branch. Try downloading that code, recompiling, and trying again. 
As an alternative, open the ui.xaml.cs file and search for 'VMATplan.OptimizationSetup.UseJawTracking = true;'

Replace that line with the follow lines:
try { VMATplan.OptimizationSetup.UseJawTracking = true; }
catch (Exception except) { MessageBox.Show(String.Format("Warning! Could not set jaw tracking to true for VMAT plan because: {0}\nJaw tacking will not be enabled!", except.Message)); }

**Comment by Erhushenshou** [comment]
But our machine do support jaw tracking in vmat. When we do vmat, we would click on jaw tacking on optimization page. Another thing, we are citrix user. Do we have to buid the code on citrix server? I just build on Tbox and copy the folder to citrix va_transfer nad open in varian cloud.

**Comment by Erhushenshou** [comment]
Seemed that this line"at VMATTBIautoPlan.UI.setOptConst_Click(Object sender, RoutedEventArgs e) in C:\Users\Varian\Desktop\VMAT-TBI-beta\VMAT-TBI-beta\ESAPI\Projects\VMATTBIautoPlan\UI.xaml.cs:line 1272" directed to the path in our Tbox, not in path of the script in cirtrix server.

**Comment by esimiele** [comment]
Interesting. I'm not super concerned about the paths pointing to your t-box even when the script is run from Citrix. The likely reason for the mismatching paths is due to the way the code was compiled (debug mode), which keeps track of the absolute location of all the files when the code was compiled. So when the .dll file is executed from a location other than the default and crashes, it will likely point to the location of the offending file (and line number) when the code was compiled. I'm guessing you downloaded the code to the t-box, recompiled, and then later migrated the VMAT-TBI folder to a shared drive that was visible by citrix without recompiling? You shouldn't need to recompile for switching between the t-box and the clinical system.

If everything ran fine in the T-box and it crashes in the clinical system, there is likely some difference in the configuration of the two Aria systems (I agree with the comment from: https://www.reddit.com/r/esapi/comments/ucidlp/jaw_tracking_not_supported/). Could you have a look and ensure the configuration for the machine of interest is the same between the t-box and clinical systems?  
Let me know what you find. If the machines are identical between the two systems, it will require a bit more digging to find the issue.

**Comment by Erhushenshou** [comment]
Thank you. It is now fixed.
